### ISSUE TITLE
大佬，请教一下三个方法执行时机如何控制在自定义的so加载后

### ISSUE THREAD

**Issue by YenKoc** [RikkaApps/Riru-ModuleTemplate#12]
在实现一个注入需求时，发现forkAndSpecializePost这个方法执行的时候，自定义的so还未加载进来，能请教下有啥解决办法吗

**Comment by RikkaW** [comment]
26 的 Riru 会在 Magisk 展示载入了哪些模块，哪里说什么呢？

**Comment by YenKoc** [comment]
师傅，理解错我意思了，不是riru那个启动模块启动我编写riru模板生成的so，而是我编写riru模板so时，去hook app的so，然后没hook到他的加载，而且一遍历maps查看系统so可以，但是一查看libnative-lib.so这种，就crash了，所以我实现是hook dlopen去监控so的加载，但是app的so一直没监控到，只监控到几个小so
