### ISSUE TITLE
理解错意思了，师傅，尴尬

### ISSUE THREAD

**Issue by YenKoc** [RikkaApps/Riru-ModuleTemplate#13]
师傅，理解错我意思了，不是riru那个启动模块启动我编写riru模板生成的so，而是我编写riru模板so时，去hook app的so，然后没hook到他的加载，而且一遍历maps查看系统so可以，但是一查看libnative-lib.so这种，就crash了，所以我实现是hook dlopen去监控so的加载，但是app的so一直没监控到，只监控到几个小so

**Comment by RikkaW** [comment]
乱七八糟 这听起来与 Riru 无关
